### ISSUE TITLE
An error occurred while provisioning resources (Error Type: Disconnect).

### ISSUE THREAD

**Issue by CodyBontecou** [undefinedlabs/scope-for-swift-action#13]
Every step is occurring until it gets to Scope for Swift where I get a warning messing: `Received request to deprovision: The request was cancelled by the remote provider.` and a failure message: `An error occurred while provisioning resources (Error Type: Disconnect).`

Here is the workflow file I am using:

```
name: Scope Testing

on: [push]

jobs:
  scope:
    runs-on: macOS-latest
    
    steps:
      - name: Check if SCOPE_DSN is set
        run: if [ "${{secrets.SCOPE_DSN}}" = "" ]; then exit 1; fi
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build dependencies
        run: pod install
      - name: Scope for Swift
        uses: undefinedlabs/scope-for-swift-action@v1
        with:
          dsn: ${{ secrets.SCOPE_DSN }}
          platform: ios
          codePath: true
        env:
          SCOPE_INSTRUMENTATION_HTTP_PAYLOADS: YES
```
